### ISSUE TITLE
Intégrer la connexion BrowserID

### ISSUE THREAD

**Issue by AntoineTurmel** [mozfr/wiki#1]
Permettre la connexion via BrowserID avec un plugin comme celui ci :

https://github.com/stomlinson/browserid_mediawiki_extension

**Comment by Rudloff** [comment]
Voici une ébauche d'extension :
https://svn.strasweb.fr/listing.php?repname=Pierre+Rudloff&path=%2Fmediawiki%2FMozillaPersona%2F

La connexion se fait via la page Spécial:MozillaPersona.

**Comment by Flaburgan** [comment]
Les gars sur #identity m'ont dit il y a quelques mois que yavait pas mal de problèmes à intégrer Persona sur mediawiki, tu t'en es sorti comment ?

**Comment by Rudloff** [comment]
Quels problèmes exactement ?
Je n'ai pas trouvé ça plus compliqué que pour un autre CMS.

**Comment by Rudloff** [comment]
Je l'ai installé sur un de mes wikis si vous voulez tester :
http://wiki.strasweb.fr/index.php?title=Sp%C3%A9cial:MozillaPersona
Je l'utilise depuis quelques jours et je n'ai pas rencontré de problème.

**Comment by Flaburgan** [comment]
\o/ Pierre je t'aime !!

(par contre je ne vois pas de bouton sign in... c'est où ?)

**Comment by Rudloff** [comment]
Comme je l'ai dis, sur la page Spécial:MozillaPersona pour l'instant.
Il faudra que je vois comme ajouter ça au menu.

**Comment by Rudloff** [comment]
Est-ce que c'est toujours d'actualité ?
J'ai mis l'extension sur Github et je veux bien reprendre le développement : https://github.com/Rudloff/mediawiki-persona
